apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitalsync-backend
  labels:
    app: vitalsync-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vitalsync-backend
  template:
    metadata:
      labels:
        app: vitalsync-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/lajous-harold/vitalsync-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vitalsync-db-secret
                  key: postgres-password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: vitalsync-db-secret
                  key: postgres-user
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: vitalsync-db-secret
                  key: postgres-db
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
