apiVersion: v1
kind: Secret
metadata:
  name: vitalsync-db-secret
type: Opaque
data:
  # Valeurs encodées en base64 (echo -n "valeur" | base64)
  postgres-password: dml0YWxzeW5jX3Bhc3M=
  postgres-user: dml0YWxzeW5jX3VzZXI=
  postgres-db: dml0YWxzeW5jX2Ri
